server:
  port: 9991


spring:
  application:
    name: STOCK-Calculation-Service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/   
      
#Swagger
#spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
